version: '3'

services:
  consignment-cli:
    build:
      ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  user-cli:
    build:
      ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-srv:
    build:
      ./consignment-srv
    ports:
      - 50051:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  vessel-srv:
    build:
      ./vessel-srv
    ports:
      - 50052:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  user-srv:
    build:
      ./user-srv
    ports:
      - 50053:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
